### ISSUE TITLE
Config options

### ISSUE THREAD

**Issue by effable** [sstativa/mfc-node#10]
Users should be able to set how script populates the table in terms of order (i.e. when accessing 0.0.0.0:9080, the table should be autosorted in a user-defined way). 

Additionally, is there a way to only see models included instead of all of them by default?

**Comment by sstativa** [comment]
It will be a bit tricky to create default order setting in config.yml file, however, you can manually change `index.html` file and set the default order you like. Find the lines
```js
      vm.sortType = 'nm';
      vm.sortReverse = false;
```
and change `vm.sortType` to 
* `nm` - Name 
* `vs` - State
* `camscore` - Score
* `continent` - Continent
* `new_model` - New
* `rc` - Viewers

and change `vm.sortReverse` to `true` if you need reverse order.
