### ISSUE TITLE
Convertable for Chaturbate records?

### ISSUE THREAD

**Issue by lol4dead** [sstativa/mfc-node#12]
Would love to use this script for Chaturbate.com too doe to missing Couples on MFC.
Im a absolute noobie on programming so i dont really know how much work it is but is would be fantastic if u would write this for Chaturbate too.

lol4dead

**Comment by sstativa** [comment]
Have you tried this [sstativa/capturebate-node](https://github.com/sstativa/capturebate-node)?

**Comment by lol4dead** [comment]
Yeah tryed it on Linux cuz all the other Capturebate tools requied Linux where i got tones of Error's but under Windows its working now!

Thanks bud
