### ISSUE TITLE
Checking models without loading a full list

### ISSUE THREAD

**Issue by marabu88** [sstativa/mfc-node#27]
Since the full list algorithm does not work as it should, I see only two solutions. 

1) Process messages with a constant connection to the socket, instead of creating a new connection and loading the full list of models (similar to the official application)

2) Check each model from the list of favorites without requesting a complete list. This means rejecting the interface with a selection from the full list, but it will work.

The first option implies full implementation of support for the existing protocol, instead of the trick that was used up to the present moment. But gives a huge advantage in the responsiveness of the program, as information about the models will be updated in real time.

The implementation of the second option is simpler and more stupid, but if it is possible, then it makes it possible to make the application less dependent on the protocol implementation features.

I think that the interface for obtaining information about models should be implemented as a separate object, possibly as a separate module, which, without changes, could be used for different forks of this script.

**Comment by marabu88** [comment]
I check MFCAuto. This is work fine. Why you don't use this module?

**Comment by sstativa** [comment]
v2 branch used MFCAuto for ages. I made it master.

**Comment by marabu88** [comment]
Oh..This is my biggest mistake with this project. But now my version uses MFCAuto also :)
