### ISSUE TITLE
Buy me a Coffee link

### ISSUE THREAD

**Issue by wylde780** [sstativa/mfc-node#30]
<a class="ko-fi" href='https://ko-fi.com/A320FTJ' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://az743702.vo.msecnd.net/cdn/kofi4.png?v=f' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a> 
^^ index.html

the short link is no longer working. Perhaps an issue with the shortening provider ? I'm using the most recent version. Looking forward to buying you a coffee :) 

Thanks

**Comment by wylde780** [comment]
It works now .. must have been an issue with the shortening service. Feel free to close this

**Comment by sstativa** [comment]
Thx a lot
