### ISSUE TITLE
Error with model uid: 18886696

### ISSUE THREAD

**Issue by marabu88** [sstativa/mfc-node#33]
I see some strange error with one model ( NOT FROM MY LIST):
```
[2017/07/25 - 02:19:51] [ERROR] { sid: 216122647,
  uid: 18886696,
  vs: 0,
  pid: 1,
  hidecs: true,
  rc: 1,
  camscore: 817.4,
  camserv: 967 }
```

**Comment by sstativa** [comment]
This reason of this message is absence of `nm` field inside model's record. 
That happens some time and I don't know why. I suppose MFC servers send malformed messages sometimes.
