### ISSUE TITLE
ffmpeg record streams with errors now

### ISSUE THREAD

**Issue by marabu88** [sstativa/mfc-node#37]
During the last time (about 2 weeks) the streams are being sorted out of me with a lot of mistakes. I created a script to generate a preview with ffmpeg. Everything was fine before (with rare exceptions), but now the timecode in the screenshots and in the video does not match, as there are skips during the recording that are ignored when creating screenshots. Earlier this happened only sometimes, now in every video :( I do not know how to find the reason, if someone does the same thing - write .can there be a reason on my Internet? Theoretically, the Internet has a speed of 100 mbps and I do not notice any problems With a different type of content.

The ping command indicates that the packet loss to the video server is not present, and the response rate is about 200 ms

I try use ffmpeg for convert .ts to .mvk and have this error :(

 ```
ffmpeg -i "Effie_Bunny_2017-08-10_20-05-40.ts" -vcodec copy -acodec copy "Effie_Bunny_2017-08-10_20-05-40.mkv"

ffmpeg version N-86950-g1bef008 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 70.100 / 55. 70.100
  libavcodec     57.102.100 / 57.102.100
  libavformat    57. 76.100 / 57. 76.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 98.100 /  6. 98.100
  libswscale      4.  7.102 /  4.  7.102
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, mpegts, from 'G:\MFCRecorder2+\Recordings\24913270 - Effie_Bunny\Effie_Bunny_2017-08-10_20-05-40.ts':
  Duration: 00:40:45.68, start: 1.400000, bitrate: 331 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, progressive), 320x240 [SAR 1:1 DAR 4:3], 24 fps, 7.50 tbr, 90k tbn, 48 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 16000 Hz, mono, fltp, 37 kb/s
Output #0, matroska, to 'Effie_Bunny_2017-08-10_20-05-40.mkv':
  Metadata:
    encoder         : Lavf57.76.100
    Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuv420p(tv, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 24 fps, 7.50 tbr, 1k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 16000 Hz, mono, fltp, 37 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 000000000296e200] Non-monotonous DTS in output stream 0:1; previous: 90176, current: 90108; changing to 90176. This may result in incorrect timestamps in the output file.
[matroska @ 000000000296e200] Non-monotonous DTS in output stream 0:1; previous: 90176, current: 90172; changing to 90176. This may result in incorrect timestamps in the output file.
[AVBSFContext @ 0000000002a14aa0] Error parsing ADTS frame header!
[AVBSFContext @ 0000000002a14aa0] Failed to send packet to filter aac_adtstoasc for stream 0
av_interleaved_write_frame(): Invalid data found when processing input
frame= 1144 fps=0.0 q=-1.0 Lsize=    6473kB time=00:02:40.92 bitrate= 329.5kbits/s speed=2.51e+003x
video:5864kB audio:598kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.159981%
Conversion failed!
```

**Comment by marabu88** [comment]
No one has a similar problem? These problems are present with the original script and with my fork. 

Also i have this error from ffmpeg very offten. 
```
[h264 @ 00000000026ddfe0] Invalid NAL unit 6, skipping.rate=N/A speed= 339x
[h264 @ 00000000026ddfe0] negative number of zero coeffs at 31 1
[h264 @ 00000000026ddfe0] error while decoding MB 31 1
[h264 @ 00000000026ddfe0] concealing 1178 DC, 1178 AC, 1178 MV errors in P frame
```
Could this be the result of the DPI equipment running at the ISP, updating the version of windows 10? Any ideas, please! I'm just losing pieces of streams for any models (HD and not HD).

Dear developer of the original script, in the text of the program there is a function for writing the stream through Rtmp

```
Function createRtmpCaptureProcess (myModel) {
   // "classified", currently I'm not interested in make this part public
}
```
I'm very interested in publishing this code :) Maybe this is the solution to my problem.

**Comment by marabu88** [comment]
And script what i use for create thumbnails (this is for Windows):

video2images_1.2.bat
```
@FOR %%A IN (%*) DO (
  @MD "%%~nA%"
  @CD "%%~nA%"
  ffmpeg -i %%A -vf "[in]fps=1/5[in2];[in2]drawtext=fontfile='C\:\\Windows\\Fonts\\arial.ttf':x=10:y=10:fontsize=24:fontcolor=yellow@0.8:box=1:boxborderw=4:boxcolor=black@0.3:textfile='burn-in.txt'[out]" "%~n1_%%07d.jpg"
  @CD ..
)
```
burn-in.txt
`%{pts:gmtime:0:'%H:%M:%S'}`

Now, the timestamps on the screenshots do not match the time in the video player. Before everything worked perfectly. Please, check with yourself the same way. Maybe you just did not pay attention to it.

**Comment by sstativa** [comment]
I have no answer on your question. 
However, I'll recommend you to try to convert files from ts to mp4 using `convert.js` and only then to generate thumbs. One of the "feature" of `convert.js` is to attempt to sync video and audio streams. 

Another option would be is to add video server number to filename and then check if there any correlation between video servers and broken files. It might be the issue with some servers only.

**Comment by marabu88** [comment]
I'm afraid you do not understand the seriousness of my (or not only mine) problem. Converting video into a different format or creating screenshots are needed only to show (or check) that the stream is periodically interrupted and its parts are lost forever. When converting these pieces are cut out and the synchronization of audio and video here is completely irrelevant.

I do not understand why this happens. I do not have the faintest idea of whether any of you have a problem of this kind (and for this I suggested comparing the length of the original file and the file after conversion).

It now happens absolutely with any video stream.  I ran 4 options for recording video streams - my script, your script, your script writing via streamlink, separate bat-files that use streamlink in an infinite loop. In all cases, video streams are periodically interrupted :(

**Comment by sstativa** [comment]
Script is just a "wrapper" on top of ffmpeg. Changing scripts will change nothing.

I'm not sure how can I help you. Probably some ffmpeg parameters could minify you problem, but I doubt this, my guess will be that you've never received missing parts, and there can be plenty of reasons for this: your HDD, number of streams you record, your ISP, MFC servers, model's ISP, her location, etc.

Probably the best for you will be to create another "test lab" and record the same models for a while then compare results. 

If you worry only about `Non-monotonous DTS in output stream` then ignore it, it was always the case, especially for rtmp streams. 

At the end, this is just "live" stream, if you missed something - it's gone.

**Comment by marabu88** [comment]
How i think streamlink don't use ffmpeg for record hls-streams. In addition, this utility has many settings that I could not find from ffmpeg. Do you know any settings that you can change so that the pieces of the stream do not disappear? All I tried to do was not result in the desired result :(

I also noticed that the streams that I write with ffmpeg (on different disks) are not identical and omissions occur in different places. Of course, these streams start to be recorded not simultaneously, but with a small difference, since the models are checked every 30 seconds.

The streams that I write using streamlink are simply broken up into a large number of pieces. I do not understand what could be causing this. Earlier, under exactly the same conditions, everything worked fine.

The speed of my internet is 100 mbit / s. Ping shows a stable connection to MFC servers.

I ran a recording of one model on a laptop that is connected to the same router. If this is only my problem, then maybe me should check the router. But I still doubt that this is my personal problem.

Can you send me some original videos WITHOUT converting? Duration of more than 30 minutes and a size of more than 100 mb?

**Comment by marabu88** [comment]
Somebody will explain to me why when processing the original ts-file using ffmpeg I get a lot of these errors? Before this was not!

```
[h264 @ 0000000002a645c0] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a645c0] negative number of zero coeffs at 9 7
[h264 @ 0000000002a645c0] error while decoding MB 9 7
[h264 @ 0000000002a645c0] concealing 200 DC, 200 AC, 200 MV errors in P frame
[h264 @ 0000000002794240] Invalid NAL unit 0, skipping.
[h264 @ 0000000002794240] out of range intra chroma pred mode
[h264 @ 0000000002794240] error while decoding MB 15 9
[h264 @ 0000000002794240] concealing 154 DC, 154 AC, 154 MV errors in I frame
[h264 @ 00000000027920a0] Invalid NAL unit 6, skipping.
[h264 @ 00000000027920a0] corrupted macroblock 1 6 (total_coeff=-1)
[h264 @ 00000000027920a0] error while decoding MB 1 6
[h264 @ 00000000027920a0] concealing 228 DC, 228 AC, 228 MV errors in P frame
[h264 @ 0000000002ab8180] Invalid NAL unit 6, skipping.rate=N/A speed= 144x
[h264 @ 0000000002ab8180] corrupted macroblock 11 11 (total_coeff=-1)
[h264 @ 0000000002ab8180] error while decoding MB 11 11
[h264 @ 0000000002ab8180] concealing 118 DC, 118 AC, 118 MV errors in P frame
[h264 @ 0000000002a64f40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a64f40] corrupted macroblock 10 13 (total_coeff=-1)
[h264 @ 0000000002a64f40] error while decoding MB 10 13
[h264 @ 0000000002a64f40] concealing 79 DC, 79 AC, 79 MV errors in P frame
[h264 @ 0000000002a656e0] negative number of zero coeffs at 2 14speed= 145x
[h264 @ 0000000002a656e0] error while decoding MB 2 14
[h264 @ 0000000002a656e0] concealing 67 DC, 67 AC, 67 MV errors in P frame
```
[h264 @ 0000000002a64a80] Invalid NAL unit 6, skipping.rate=N/A speed= 150x
[h264 @ 0000000002a64a80] Invalid level prefix
[h264 @ 0000000002a64a80] error while decoding MB 10 8
[h264 @ 0000000002a64a80] concealing 179 DC, 179 AC, 179 MV errors in P frame
[h264 @ 0000000002792a40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002792a40] negative number of zero coeffs at 7 8
[h264 @ 0000000002792a40] error while decoding MB 7 8
[h264 @ 0000000002792a40] concealing 182 DC, 182 AC, 182 MV errors in P frame
[h264 @ 0000000002695880] Invalid NAL unit 6, skipping.
[h264 @ 0000000002695880] negative number of zero coeffs at 14 12
[h264 @ 0000000002695880] error while decoding MB 14 12
[h264 @ 0000000002695880] concealing 95 DC, 95 AC, 95 MV errors in P frame
[h264 @ 0000000002a64a80] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a64a80] Invalid level prefix
[h264 @ 0000000002a64a80] error while decoding MB 9 0
[h264 @ 0000000002a64a80] concealing 300 DC, 300 AC, 300 MV errors in P frame
[h264 @ 0000000002a645c0] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a645c0] Invalid level prefix
[h264 @ 0000000002a645c0] error while decoding MB 11 8
[h264 @ 0000000002a645c0] concealing 178 DC, 178 AC, 178 MV errors in P frame
[h264 @ 00000000026d6b60] Invalid NAL unit 6, skipping.rate=N/A speed= 150x
[h264 @ 00000000026d6b60] negative number of zero coeffs at 11 2
[h264 @ 00000000026d6b60] error while decoding MB 11 2
[h264 @ 00000000026d6b60] concealing 298 DC, 298 AC, 298 MV errors in P frame
[h264 @ 00000000027920a0] Invalid NAL unit 6, skipping.rate=N/A speed= 153x
[h264 @ 00000000027920a0] negative number of zero coeffs at 8 10
[h264 @ 00000000027920a0] error while decoding MB 8 10
[h264 @ 00000000027920a0] concealing 141 DC, 141 AC, 141 MV errors in P frame
[h264 @ 0000000002a64100] Invalid NAL unit 0, skipping.rate=N/A speed= 157x
Invalid UE golomb code
[h264 @ 0000000002a64100] mb_type -1094995529 in I slice too large at 11 0
[h264 @ 0000000002a64100] error while decoding MB 11 0
[h264 @ 0000000002a64100] concealing 300 DC, 300 AC, 300 MV errors in I frame
[h264 @ 0000000002a64f40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a64f40] Invalid level prefix
[h264 @ 0000000002a64f40] error while decoding MB 6 1
[h264 @ 0000000002a64f40] concealing 300 DC, 300 AC, 300 MV errors in P frame
[h264 @ 0000000002695880] Invalid NAL unit 6, skipping.
[h264 @ 0000000002695880] Invalid level prefix
[h264 @ 0000000002695880] error while decoding MB 12 0
[h264 @ 0000000002695880] concealing 300 DC, 300 AC, 300 MV errors in P frame
[h264 @ 00000000027933e0] Invalid NAL unit 6, skipping.
[h264 @ 00000000027933e0] corrupted macroblock 18 4 (total_coeff=-1)
[h264 @ 00000000027933e0] error while decoding MB 18 4
[h264 @ 00000000027933e0] concealing 251 DC, 251 AC, 251 MV errors in P frame
[h264 @ 0000000002794240] Invalid NAL unit 0, skipping.
[h264 @ 0000000002794240] negative number of zero coeffs at 15 3
[h264 @ 0000000002794240] error while decoding MB 15 3
[h264 @ 0000000002794240] concealing 274 DC, 274 AC, 274 MV errors in I frame
[h264 @ 0000000002695880] Invalid NAL unit 6, skipping.rate=N/A speed= 155x
[h264 @ 0000000002695880] corrupted macroblock 12 7 (total_coeff=-1)
[h264 @ 0000000002695880] error while decoding MB 12 7
[h264 @ 0000000002695880] concealing 197 DC, 197 AC, 197 MV errors in P frame
[h264 @ 0000000002695880] Invalid NAL unit 6, skipping.
[h264 @ 0000000002695880] Invalid level prefix
[h264 @ 0000000002695880] error while decoding MB 8 2
[h264 @ 0000000002695880] concealing 300 DC, 300 AC, 300 MV errors in P frame
[h264 @ 0000000002a64a80] Invalid NAL unit 6, skipping.rate=N/A speed= 154x
[h264 @ 0000000002a64a80] Invalid level prefix
[h264 @ 0000000002a64a80] error while decoding MB 5 14
[h264 @ 0000000002a64a80] concealing 64 DC, 64 AC, 64 MV errors in P frame
[h264 @ 00000000026d6b60] Invalid NAL unit 6, skipping.rate=N/A speed= 156x
[h264 @ 00000000026d6b60] Invalid level prefix
[h264 @ 00000000026d6b60] error while decoding MB 0 7
[h264 @ 00000000026d6b60] concealing 209 DC, 209 AC, 209 MV errors in P frame
[h264 @ 0000000002792a40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002792a40] corrupted macroblock 14 14 (total_coeff=-1)
[h264 @ 0000000002792a40] error while decoding MB 14 14
[h264 @ 0000000002792a40] concealing 55 DC, 55 AC, 55 MV errors in P frame
[h264 @ 0000000002793d80] Invalid NAL unit 6, skipping.rate=N/A speed= 155x
[h264 @ 0000000002793d80] corrupted macroblock 14 7 (total_coeff=-1)
[h264 @ 0000000002793d80] error while decoding MB 14 7
[h264 @ 0000000002793d80] concealing 195 DC, 195 AC, 195 MV errors in P frame
[h264 @ 00000000026d6b60] Invalid NAL unit 6, skipping.
Invalid UE golomb code
[h264 @ 00000000026d6b60] mb_type -1094995534 in P slice too large at 13 7
[h264 @ 00000000026d6b60] error while decoding MB 13 7
[h264 @ 00000000026d6b60] concealing 196 DC, 196 AC, 196 MV errors in P frame
[h264 @ 0000000002a656e0] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a656e0] Invalid level prefix
[h264 @ 0000000002a656e0] error while decoding MB 6 2
[h264 @ 0000000002a656e0] concealing 300 DC, 300 AC, 300 MV errors in P frame
[h264 @ 0000000002793d80] Invalid NAL unit 0, skipping.rate=N/A speed= 151x
[h264 @ 0000000002793d80] Invalid level prefix
[h264 @ 0000000002793d80] error while decoding MB 6 10
[h264 @ 0000000002793d80] concealing 143 DC, 143 AC, 143 MV errors in I frame
[h264 @ 00000000027933e0] Invalid NAL unit 6, skipping.rate=N/A speed= 151x
[h264 @ 00000000027933e0] negative number of zero coeffs at 4 8
[h264 @ 00000000027933e0] error while decoding MB 4 8
[h264 @ 00000000027933e0] concealing 185 DC, 185 AC, 185 MV errors in P frame
[h264 @ 0000000002792a40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002792a40] corrupted macroblock 0 13 (total_coeff=-1)
[h264 @ 0000000002792a40] error while decoding MB 0 13
[h264 @ 0000000002792a40] concealing 89 DC, 89 AC, 89 MV errors in P frame
[h264 @ 0000000002a645c0] Invalid NAL unit 6, skipping.rate=N/A speed= 150x
[h264 @ 0000000002a645c0] corrupted macroblock 11 11 (total_coeff=-1)
[h264 @ 0000000002a645c0] error while decoding MB 11 11
[h264 @ 0000000002a645c0] concealing 118 DC, 118 AC, 118 MV errors in P frame
[h264 @ 00000000027920a0] Invalid NAL unit 6, skipping.rate=N/A speed= 150x
[h264 @ 00000000027920a0] corrupted macroblock 15 5 (total_coeff=-1)
[h264 @ 00000000027920a0] error while decoding MB 15 5
[h264 @ 00000000027920a0] concealing 234 DC, 234 AC, 234 MV errors in P frame
[h264 @ 0000000002794240] Invalid NAL unit 6, skipping.
[h264 @ 0000000002794240] Invalid level prefix
[h264 @ 0000000002794240] error while decoding MB 12 12
[h264 @ 0000000002794240] concealing 97 DC, 97 AC, 97 MV errors in P frame
[h264 @ 0000000002792a40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002792a40] Invalid level prefix
[h264 @ 0000000002792a40] error while decoding MB 14 12
[h264 @ 0000000002792a40] concealing 95 DC, 95 AC, 95 MV errors in P frame
[h264 @ 0000000002a64100] Invalid NAL unit 6, skipping.rate=N/A speed= 150x
[h264 @ 0000000002a64100] corrupted macroblock 13 13 (total_coeff=-1)
[h264 @ 0000000002a64100] error while decoding MB 13 13
[h264 @ 0000000002a64100] concealing 76 DC, 76 AC, 76 MV errors in P frame
[h264 @ 0000000002a64f40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a64f40] Invalid level prefix
[h264 @ 0000000002a64f40] error while decoding MB 2 8
[h264 @ 0000000002a64f40] concealing 187 DC, 187 AC, 187 MV errors in P frame
[h264 @ 0000000002695880] Invalid NAL unit 6, skipping.
[h264 @ 0000000002695880] negative number of zero coeffs at 1 14
[h264 @ 0000000002695880] error while decoding MB 1 14
[h264 @ 0000000002695880] concealing 68 DC, 68 AC, 68 MV errors in P frame
[h264 @ 0000000002a645c0] Invalid NAL unit 6, skipping.rate=N/A speed= 152x
[h264 @ 0000000002a645c0] negative number of zero coeffs at 0 13
[h264 @ 0000000002a645c0] error while decoding MB 0 13
[h264 @ 0000000002a645c0] concealing 89 DC, 89 AC, 89 MV errors in P frame
[h264 @ 0000000002792a40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002792a40] Invalid level prefix
[h264 @ 0000000002792a40] error while decoding MB 16 2
[h264 @ 0000000002792a40] concealing 293 DC, 293 AC, 293 MV errors in P frame
[h264 @ 0000000002ab8180] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a64a80] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a64a80] Invalid level prefix15.00 bitrate=N/A speed= 152x
[h264 @ 0000000002a64a80] error while decoding MB 6 9
[h264 @ 0000000002a64a80] concealing 163 DC, 163 AC, 163 MV errors in P frame
[h264 @ 0000000002793d80] Invalid NAL unit 6, skipping.
[h264 @ 0000000002793d80] Invalid level prefix
[h264 @ 0000000002793d80] error while decoding MB 15 6
[h264 @ 0000000002793d80] concealing 214 DC, 214 AC, 214 MV errors in P frame
[h264 @ 0000000002a64f40] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a64f40] corrupted macroblock 12 10 (total_coeff=-1)
[h264 @ 0000000002a64f40] error while decoding MB 12 10
[h264 @ 0000000002a64f40] concealing 137 DC, 137 AC, 137 MV errors in P frame
[h264 @ 0000000002a64f40] Invalid NAL unit 0, skipping.
[h264 @ 0000000002a64f40] Invalid level prefix
[h264 @ 0000000002a64f40] error while decoding MB 3 10
[h264 @ 0000000002a64f40] concealing 146 DC, 146 AC, 146 MV errors in I frame
[h264 @ 00000000027920a0] Invalid NAL unit 6, skipping.rate=N/A speed= 153x
[h264 @ 00000000027920a0] negative number of zero coeffs at 19 8
[h264 @ 00000000027920a0] error while decoding MB 19 8
[h264 @ 00000000027920a0] concealing 170 DC, 170 AC, 170 MV errors in P frame
[h264 @ 00000000026d6b60] Invalid NAL unit 6, skipping.rate=N/A speed= 155x
[h264 @ 00000000026d6b60] Invalid level prefix
[h264 @ 00000000026d6b60] error while decoding MB 1 0
[h264 @ 00000000026d6b60] concealing 300 DC, 300 AC, 300 MV errors in P frame
[h264 @ 0000000002ab8180] Invalid NAL unit 6, skipping.
[h264 @ 0000000002ab8180] dquant out of range (104) at 19 12
[h264 @ 0000000002ab8180] error while decoding MB 19 12
[h264 @ 0000000002ab8180] concealing 90 DC, 90 AC, 90 MV errors in P frame
[h264 @ 0000000002a656e0] Invalid NAL unit 6, skipping.rate=N/A speed= 157x
[h264 @ 0000000002a656e0] Invalid level prefix
[h264 @ 0000000002a656e0] error while decoding MB 12 4
[h264 @ 0000000002a656e0] concealing 257 DC, 257 AC, 257 MV errors in P frame
[h264 @ 0000000002a64a80] Invalid NAL unit 6, skipping.
[h264 @ 0000000002a64a80] negative number of zero coeffs at 9 7
[h264 @ 0000000002a64a80] error while decoding MB 9 7
[h264 @ 0000000002a64a80] concealing 200 DC, 200 AC, 200 MV errors in P frame
[h264 @ 0000000002a64100] Invalid level prefix
[h264 @ 0000000002a64100] error while decoding MB 10 0
[h264 @ 0000000002a64100] concealing 300 DC, 300 AC, 300 MV errors in P frame
[h264 @ 0000000002a64a80] Invalid NAL unit 6, skipping.rate=N/A speed= 157x
[h264 @ 0000000002a64a80] Invalid level prefix
[h264 @ 0000000002a64a80] error while decoding MB 5 12
[h264 @ 0000000002a64a80] concealing 104 DC, 104 AC, 104 MV errors in P frame
[h264 @ 0000000002ab8180] Invalid NAL unit 6, skipping.
[h264 @ 0000000002ab8180] negative number of zero coeffs at 0 0
[h264 @ 0000000002ab8180] error while decoding MB 0 0
[h264 @ 0000000002ab8180] concealing 300 DC, 300 AC, 300 MV errors in P frame
[h264 @ 00000000027933e0] Invalid NAL unit 6, skipping.rate=N/A speed= 157x
[h264 @ 00000000027933e0] negative number of zero coeffs at 9 9
[h264 @ 00000000027933e0] error while decoding MB 9 9
[h264 @ 00000000027933e0] concealing 160 DC, 160 AC, 160 MV errors in P frame
[h264 @ 0000000002a645c0] corrupted macroblock 7 3 (total_coeff=-1)
[h264 @ 0000000002a645c0] error while decoding MB 7 3
[h264 @ 0000000002a645c0] concealing 282 DC, 282 AC, 282 MV errors in P frame
[h264 @ 00000000027920a0] corrupted macroblock 11 6 (total_coeff=-1)
[h264 @ 00000000027920a0] error while decoding MB 11 6
[h264 @ 00000000027920a0] concealing 218 DC, 218 AC, 218 MV errors in P frame
[h264 @ 0000000002792a40] Invalid NAL unit 6, skipping.rate=N/A speed= 156x
[h264 @ 0000000002792a40] Invalid level prefix
[h264 @ 0000000002792a40] error while decoding MB 16 9
[h264 @ 0000000002792a40] concealing 153 DC, 153 AC, 153 MV errors in P frame
[h264 @ 0000000002ab8180] Invalid NAL unit 6, skipping.
[h264 @ 0000000002ab8180] Invalid level prefix
[h264 @ 0000000002ab8180] error while decoding MB 14 9
[h264 @ 0000000002ab8180] concealing 155 DC, 155 AC, 155 MV errors in P frame
[h264 @ 0000000002ab8180] Invalid NAL unit 6, skipping.rate=N/A speed= 157x
[h264 @ 0000000002ab8180] cbp too large (415) at 18 2
[h264 @ 0000000002ab8180] error while decoding MB 18 2
[h264 @ 0000000002ab8180] concealing 291 DC, 291 AC, 291 MV errors in P frame
[h264 @ 00000000027920a0] Invalid level prefix55.00 bitrate=N/A speed= 155x

**Comment by marabu88** [comment]
> I'm not sure how can I help you. Probably some ffmpeg parameters could minify you problem, but I doubt this, my guess will be that you've never received missing parts, and there can be plenty of reasons for this: your HDD, number of streams you record, your ISP, MFC servers, model's ISP, her location, etc.
> Probably the best for you will be to create another "test lab" and record the same models for a while then compare results.

I try record same model in another computer and asked a friend to record a video on his computer. The problem persists. But my friend uses the same ISP. You say that one of the reasons may be my ISP. Can this be true if I have the perfect ping with MFC video servers? I have a channel of 100 bpm and it is rarely used completely

**Comment by sstativa** [comment]
The issue belongs to ISP.
