### ISSUE TITLE
rtmp 

### ISSUE THREAD

**Issue by marabu88** [sstativa/mfc-node#39]
I don't know have anyone problems with ffmpeg-recorder, but i think this is problem with servers mfc (or with ffmpeg). Ffmpeg has problems with downloading a stream in this format (.ts) in some cases. This utility is not perfect, but I do not know the alternatives to try another option :(

But main way for MFC - flv-streams and rtmp-protocol. Please help me realise this way for record streams from MFC!!! If you have any worked solution - publick it please am here or tell me where i can see it.

This is really BIG problem now.

**Comment by marabu88** [comment]
I tried to manually compile the correct string for rtmpdump, but this for some reason does not work

`rtmpdump -W "http://m.myfreecams.com/app/flash/Video170322.swf" -s "http://m.myfreecams.com/app/flash/Video170322.swf" -a "NxServer" -f "WIN 26,0,0,151" -t "rtmp://video854.myfreecams.com:1935/NxServer" -r "rtmp://video854.myfreecams.com:1935/NxServer/mp4:mfc_111972850.f4v" -p "http://www.myfreecams.com" -C N:179102170 -C N:111972850 -C S: -C S:DOWNLOAD -C N:11972850 -y "mp4:mfc_111972850.f4v" -o test.f4v --live -V`

result this command 

```
RTMPDump v2.4 GIT-2015-12-14 (Compiled by KSV)
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
DEBUG: Protocol : RTMP
DEBUG: Hostname : video854.myfreecams.com
DEBUG: Port     : 1935
DEBUG: Playpath : mp4:mfc_111972850.f4v
DEBUG: tcUrl    : rtmp://video854.myfreecams.com:1935/NxServer
DEBUG: swfUrl   : http://m.myfreecams.com/app/flash/Video170322.swf
DEBUG: pageUrl  : http://www.myfreecams.com
DEBUG: app      : NxServer
DEBUG: flashVer : WIN 26,0,0,151
DEBUG: live     : yes
DEBUG: timeout  : 30 sec
DEBUG: SWFSHA256:
DEBUG: 4c 5c dd c0 3c 7d 7f 5a 91 a5 32 49 12 0c 7f 57
DEBUG: 9d 39 ea 1a ea 7d 66 5f 39 ec 20 0b b8 c9 97 d7
DEBUG: SWFSize  : 501749
DEBUG: Setting buffer time to: 36000000ms
Connecting ...
DEBUG: RTMP_Connect1, ... connected, handshaking
DEBUG: HandShake: Client type: 03
DEBUG: HandShake: Client digest offset: 160
DEBUG: HandShake: Initial client digest:
DEBUG: 8a a4 f6 29 38 37 ad 7b 5f b1 93 a0 bc 52 61 b3
DEBUG: a0 49 19 ef ba 25 73 ef e2 85 e9 da 40 55 d1 ae
DEBUG: HandShake: Type Answer   : 03
DEBUG: HandShake: Server Uptime : 96850052
DEBUG: HandShake: FMS Version   : 3.0.1.1
DEBUG: HandShake: Calculated digest key from secure key and server digest:
DEBUG: 9e ed a0 e9 fc b3 3f d8 7e 08 1f 41 80 75 a1 bb
DEBUG: a5 5c ec c1 5f 4c 3d f0 27 7f 69 ae b0 f9 45 47
DEBUG: HandShake: Client signature calculated:
DEBUG: 26 ac fd 77 a9 85 64 c6 3e 18 70 0d f0 34 cf 45
DEBUG: 95 15 eb d9 12 1f f5 1e 21 84 12 8d 96 33 40 64
DEBUG: HandShake: Server sent signature:
DEBUG: 1e 27 87 ad 47 dd eb 1a bf 25 db 2c de da dc c5
DEBUG: e6 39 df 62 54 19 e2 a3 6a f6 f8 d4 ef 1d 27 7a
DEBUG: HandShake: Digest key:
DEBUG: 49 45 28 fa 39 2a 12 ce 98 8e a9 16 70 30 32 1f
DEBUG: bc a6 2b 9e b9 31 29 36 a4 30 8f a1 08 0a 62 dc
DEBUG: HandShake: Signature calculated:
DEBUG: 1e 27 87 ad 47 dd eb 1a bf 25 db 2c de da dc c5
DEBUG: e6 39 df 62 54 19 e2 a3 6a f6 f8 d4 ef 1d 27 7a
DEBUG: HandShake: Genuine Adobe Flash Media Server
DEBUG: HandShake: Handshaking finished....
DEBUG: RTMP_Connect1, handshaked
DEBUG: Invoking connect
INFO: Connected...
DEBUG: HandleServerBW: server BW = 2500000
DEBUG: HandleClientBW: client BW = 2500000 2
DEBUG: HandleCtrl, received ctrl, type: 0, len: 6
DEBUG: HandleCtrl, Stream Begin 0
DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
DEBUG: RTMP_ClientPacket, received: invoke 261 bytes
DEBUG: (object begin)
DEBUG: Property: <Name:            no-name, STRING:     _result>
DEBUG: Property: <Name:            no-name, NUMBER:     1.00>
DEBUG: Property: <Name:            no-name, OBJECT>
DEBUG: (object begin)
DEBUG: Property: <Name:             fmsVer, STRING:     FMS/3,5,7,7009>
DEBUG: Property: <Name:       capabilities, NUMBER:     31.00>
DEBUG: Property: <Name:               mode, NUMBER:     1.00>
DEBUG: (object end)
DEBUG: Property: <Name:            no-name, OBJECT>
DEBUG: (object begin)
DEBUG: Property: <Name:              level, STRING:     status>
DEBUG: Property: <Name:               code, STRING:     NetConnection.Connect.Success>
DEBUG: Property: <Name:        description, STRING:     Connection succeeded.>
DEBUG: Property: <Name:               data, ECMA_ARRAY>
DEBUG: (object begin)
DEBUG: Property: <Name:            version, STRING:     3,5,7,7009>
DEBUG: (object end)
DEBUG: Property: <Name:           clientid, NUMBER:     1079798588.00>
DEBUG: Property: <Name:     objectEncoding, NUMBER:     3.00>
DEBUG: (object end)
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <_result>
DEBUG: HandleInvoke, received result for method call <connect>
DEBUG: sending ctrl, type: 0x0003
DEBUG: Invoking createStream
DEBUG: Socket closed by server, nBytes: 0
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
DEBUG: Closing connection.
```

**Comment by horacio9a** [comment]
I was trying something on the subject but obviously did not fall on the fertile ground so I quickly closed that subject.
Look: [https://github.com/streamlink/streamlink/issues/901](url)
In any case, you should forget standard rtmpdump.exe versions for MFC. Maybe @edge from SR forum could make some version of rtmpdump.exe for MFC. 
Streamlink certainly works well with the MFC and my suggestion is to focus on it.

**Comment by sstativa** [comment]
Let's do it this way, if one day I rich the goal in 333 coffees, I'll release my private version of the script with rtmpdump support.

You could say that I got greedy and probably you are right, but the lack of support discourages me from doing anything else with the script. Ffmpeg version still does a pretty good job.

This is an example of rtmpdump log, it shows how it should be.
```
[08/18/2017 - 23:44:37] SimplyPaxton is now online, starting capturing process
[08/18/2017 - 23:44:37] Done, will search for new models in 30 second(s).
[08/18/2017 - 23:44:37] DEBUG: Protocol : RTMP
DEBUG: Hostname : video858.myfreecams.com
DEBUG: Port     : 1935
DEBUG: Playpath : mp4:mfc_105676470.f4v
DEBUG: tcUrl    : rtmp://video858.myfreecams.com:1935/NxServer
DEBUG: swfUrl   : http://www.myfreecams.com/flash/Video170322.swf
DEBUG: pageUrl  : https://www.myfreecams.com/_html/player.html?broadcaster_id=0&cache_id=1485777695&target=main
DEBUG: app      : NxServer
DEBUG: flashVer : WIN 25,0,0,127
DEBUG: live     : no
DEBUG: timeout  : 30 sec
DEBUG: SWFSHA256:
DEBUG: 4c 5c dd c0 3c 7d 7f 5a 91 a5 32 49 12 0c 7f 57
DEBUG: 9d 39 ea 1a ea 7d 66 5f 39 ec 20 0b b8 c9 97 d7
DEBUG: SWFSize  : 501749

[08/18/2017 - 23:44:37] DEBUG: Setting buffer time to: 36000000ms
Connecting ...

[08/18/2017 - 23:44:37] DEBUG: RTMP_Connect1, ... connected, handshaking
DEBUG: HandShake: Client type: 03

[08/18/2017 - 23:44:37] DEBUG: HandShake: Client digest offset: 417
DEBUG: HandShake: Initial client digest: 
DEBUG: af 97 43 5f f2 36 74 67 85 ac 24 6f 6f 18 6d e0
DEBUG: ef b2 ec 4a 43 f6 42 f3 39 3f 00 5d b1 d5 31 25

[08/18/2017 - 23:44:38] DEBUG: HandShake: Type Answer   : 03

[08/18/2017 - 23:44:38] DEBUG: HandShake: Server Uptime : 96850052
DEBUG: HandShake: FMS Version   : 3.0.1.1
DEBUG: HandShake: Calculated digest key from secure key and server digest: 
DEBUG: 9e ed a0 e9 fc b3 3f d8 7e 08 1f 41 80 75 a1 bb
DEBUG: a5 5c ec c1 5f 4c 3d f0 27 7f 69 ae b0 f9 45 47
DEBUG: HandShake: Client signature calculated:
DEBUG: 09 d2 a0 ab 5d fa ef 8a 61 b0 f7 ed c4 d2 3c b1
DEBUG: 22 31 c9 7b ef 01 43 b5 76 d4 53 b5 b9 8d 49 20
DEBUG: HandShake: Server sent signature:
DEBUG: 7b 03 7e db 5a f2 33 f9 a9 75 52 f3 c5 39 92 7a
DEBUG: 7e 45 54 9c 75 8f c5 39 9b a4 78 8d 24 66 2a a6
DEBUG: HandShake: Digest key: 
DEBUG: 96 29 ee 01 7b 63 c6 ae 75 73 73 9f b6 b4 c5 2f
DEBUG: 72 65 84 1a 60 7d 93 54 6f a0 ef bd 7a 62 64 a1
DEBUG: HandShake: Signature calculated:
DEBUG: 7b 03 7e db 5a f2 33 f9 a9 75 52 f3 c5 39 92 7a
DEBUG: 7e 45 54 9c 75 8f c5 39 9b a4 78 8d 24 66 2a a6
DEBUG: HandShake: Genuine Adobe Flash Media Server
DEBUG: HandShake: Handshaking finished....
DEBUG: RTMP_Connect1, handshaked
DEBUG: Invoking connect
INFO: Connected...

[08/18/2017 - 23:44:38] DEBUG: HandleServerBW: server BW = 2500000
DEBUG: HandleClientBW: client BW = 2500000 2
DEBUG: HandleCtrl, received ctrl, type: 0, len: 6
DEBUG: HandleCtrl, Stream Begin 0
DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
DEBUG: RTMP_ClientPacket, received: invoke 261 bytes
DEBUG: (object begin)
DEBUG: Property: <Name:            no-name, STRING:	_result>
DEBUG: Property: <Name:            no-name, NUMBER:	1.00>
DEBUG: Property: <Name:            no-name, OBJECT>
DEBUG: (object begin)
DEBUG: Property: <Name:             fmsVer, STRING:	FMS/3,5,7,7009>
DEBUG: Property: <Name:       capabilities, NUMBER:	31.00>
DEBUG: Property: <Name:               mode, NUMBER:	1.00>
DEBUG: (object end)
DEBUG: Property: <Name:            no-name, OBJECT>
DEBUG: (object begin)
DEBUG: Property: <Name:              level, STRING:	status>
DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
DEBUG: Property: <Name:               data, ECMA_ARRAY>
DEBUG: (object begin)
DEBUG: Property: <Name:            version, STRING:	3,5,7,7009>
DEBUG: (object end)
DEBUG: Property: <Name:           clientid, NUMBER:	2060419825.00>
DEBUG: Property: <Name:     objectEncoding, NUMBER:	3.00>
DEBUG: (object end)
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <_result>
DEBUG: HandleInvoke, received result for method call <connect>
DEBUG: sending ctrl, type: 0x0003

[08/18/2017 - 23:44:38] DEBUG: RTMP_ClientPacket, flex message, size 2298 bytes, not fully supported
DEBUG: Class name: , externalizable: 0, dynamic: 1, classMembers: 0
DEBUG: class object!
DEBUG: (object begin)
DEBUG: Property: <Name:            no-name, STRING:	loginResult>
DEBUG: Property: <Name:            no-name, NUMBER:	120781448.00>
DEBUG: Property: NULL
DEBUG: Property: <Name:            no-name, OBJECT>
DEBUG: (object begin)
DEBUG: Property: <Name:             userID, NUMBER:	0.00>
DEBUG: Property: <Name:             Handle, NUMBER:	0.00>
DEBUG: Property: <Name:          challenge, STRING:	(function(){function Sa(a,b){return (a&0xFFFFFFF)+(b&0xFFFFFFF)}function S(X,n){return (X>>>n)|((X&0xffffff)<<(32-n));}function R(X,n){return (X>>>n);}function C(x,y,z){return ((x&y)^((x)&z));}function M(x,y,z){return ((x&y)^(x&z)^(y&z));}functio>
DEBUG: Property: NULL
DEBUG: (object end)
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <loginResult>

[08/18/2017 - 23:44:38] DEBUG: SendMFCLoginResult, challenge=0b64d63a04ef58e415c78c2d180348600bff029e1da0ad2a1097d6840b3af976

[08/18/2017 - 23:44:38] DEBUG: Invoking _result

[08/18/2017 - 23:44:38] DEBUG: Invoking createStream

[08/18/2017 - 23:44:38] DEBUG: RTMP_ClientPacket, flex message, size 113 bytes, not fully supported

[08/18/2017 - 23:44:38] DEBUG: Class name: , externalizable: 0, dynamic: 1, classMembers: 0
DEBUG: class object!
DEBUG: (object begin)
DEBUG: Property: <Name:            no-name, STRING:	UpdateSession>
DEBUG: Property: <Name:            no-name, NUMBER:	0.00>
DEBUG: Property: NULL
DEBUG: Property: <Name:            no-name, OBJECT>
DEBUG: (object begin)
DEBUG: Property: <Name:                cmd, NUMBER:	20.00>
DEBUG: Property: <Name:            cmdarg1, NUMBER:	181679209.00>
DEBUG: Property: <Name:            cmdarg2, NUMBER:	5676470.00>
DEBUG: Property: <Name:            cmdarg3, NUMBER:	0.00>
DEBUG: Property: <Name:            cmdarg4, NUMBER:	0.00>
DEBUG: Property: NULL
DEBUG: (object end)
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <UpdateSession>

[08/18/2017 - 23:44:38] DEBUG: RTMP_ClientPacket, flex message, size 30 bytes, not fully supported
DEBUG: (object begin)
DEBUG: Property: <Name:            no-name, STRING:	_result>
DEBUG: Property: <Name:            no-name, NUMBER:	2.00>
DEBUG: Property: NULL
DEBUG: Property: <Name:            no-name, NUMBER:	1.00>
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <_result>
DEBUG: HandleInvoke, received result for method call <createStream>
DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:mfc_105676470.f4v
DEBUG: Invoking play
DEBUG: sending ctrl, type: 0x0003

[08/18/2017 - 23:44:39] DEBUG: HandleCtrl, received ctrl, type: 0, len: 6
DEBUG: HandleCtrl, Stream Begin 1
DEBUG: RTMP_ClientPacket, received: invoke 145 bytes
DEBUG: (object begin)
DEBUG: Property: <Name:            no-name, STRING:	onStatus>
DEBUG: Property: <Name:            no-name, NUMBER:	0.00>
DEBUG: Property: NULL
DEBUG: Property: <Name:            no-name, OBJECT>
DEBUG: (object begin)
DEBUG: Property: <Name:              level, STRING:	status>
DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Reset>
DEBUG: Property: <Name:        description, STRING:	Playing and resetting mfc_105676470.f4v.>

[08/18/2017 - 23:44:39] DEBUG: Property: <Name:           clientid, NUMBER:	2060419825.00>
DEBUG: (object end)
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <onStatus>
DEBUG: HandleInvoke, onStatus: NetStream.Play.Reset
DEBUG: RTMP_ClientPacket, received: invoke 181 bytes
DEBUG: (object begin)
DEBUG: Property: <Name:            no-name, STRING:	onStatus>
DEBUG: Property: <Name:            no-name, NUMBER:	0.00>
DEBUG: Property: NULL
DEBUG: Property: <Name:            no-name, OBJECT>
DEBUG: (object begin)
DEBUG: Property: <Name:              level, STRING:	status>
DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Start>
DEBUG: Property: <Name:        description, STRING:	Started playing mfc_105676470.f4v.>
DEBUG: Property: <Name:           clientid, NUMBER:	2060419825.00>
DEBUG: Property: <Name:         isFastPlay, BOOLEAN:	FALSE>
DEBUG: Property: <Name:     timecodeOffset, STRING:	19172098L>
DEBUG: (object end)
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <onStatus>
DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
Starting download at: 0.000 kB
DEBUG: RTMP_ClientPacket, received: notify 24 bytes
DEBUG: (object begin)
DEBUG: Property: <Name:            no-name, STRING:	|RtmpSampleAccess>
DEBUG: Property: <Name:            no-name, BOOLEAN:	FALSE>
DEBUG: Property: <Name:            no-name, BOOLEAN:	FALSE>
DEBUG: (object end)
DEBUG: HandleCtrl, received ctrl, type: 32, len: 6
DEBUG: HandleCtrl, Stream BufferReady 1
DEBUG: ignoring too small video packet: size: 2

[08/18/2017 - 23:44:39] DEBUG: ignoring too small video packet: size: 2
34.638 kB / 0.02 sec
39.999 kB / 0.92 sec39] 
94.031 kB / 1.98 sec40] 
201.999 kB / 2.80 sec0] 
385.257 kB / 3.98 sec0] 
519.893 kB / 5.04 sec0] 
621.351 kB / 5.54 sec0] 
737.158 kB / 6.01 sec1] 
820.323 kB / 6.25 sec1] 
974.072 kB / 7.04 sec1] 
1069.608 kB / 7.56 sec] 
[08/18/2017 - 23:44:41] 
DEBUG: HandleCtrl, received ctrl, type: 31, len: 6
DEBUG: HandleCtrl, Stream BufferEmpty 1
DEBUG: RTMP_SendPause, 1, pauseTime=8000
DEBUG: Invoking pause

[08/18/2017 - 23:44:41] DEBUG: HandleCtrl, received ctrl, type: 32, len: 6
DEBUG: HandleCtrl, Stream BufferReady 1

1160.959 kB / 8.02 sec] 
```

**Comment by horacio9a** [comment]
In any case, it is nice to see that there is a way how force ffmpeg.exe to record the mfc server under rtmp protocol.
This example refers to: 

https://www.myfreecams.com/#SimplyPaxton
rtmp://video858.myfreecams.com/NxServer/mp4:mfc_105676470.f4v

... this model can be recorded with current version of MyFreeCams Recorder v.2.0.6 in better resolution than rtmp's only 320x240 like:

http://video858.myfreecams.com:1935/NxServer/ngrp:mfc_105676470.f4v_mobile/playlist.m3u8

I'm most interested in giving ffmpeg the ability to record the so-called 'No Mobile Feed' as for example:

https://www.myfreecams.com/#karolinesweet
rtmp://video115.myfreecams.com/NxServer/mfc_115325703

... because for 'No Mobile Feed' has no other way than rtmp protocol?!

**Comment by sstativa** [comment]
`ffmpeg.exe` cannot record rtmp protocol. I had to patch `rtmpdump` to support MFC.

I'm not sure where did you get info about 320x240, but `rtmpdump` records in max resolution straight away. However, I've been testing `ffmpeg` and `rtmpdump` versions with the same models list for a while, and I'll admin in most cases results files were identical in resolution. Only 2 times I saw `rtmp` version in better resolution than `ffmpeg` version, but never vice versa.

**Comment by horacio9a** [comment]
All right, now is much clearer. I have always known that it is in the hands of the one who knows how to patch rtmpdump.exe very strong weapon ;)
I quickly saw my mistake about 320x240 and I quickly corrected it but not fast enough to see you;)
I wrote a that error, because I still have trauma when everyone in past forced:

http://video858.myfreecams.com:1935/NxServer/mfc_105676470.f4v_aac/playlist.m3u8

with 320x240 resolution instead:

http://video858.myfreecams.com:1935/NxServer/ngrp:mfc_105676470.f4v_mobile/playlist.m3u8

... which will enable better resolution, most often 800x600

But in one i'm sure, all the so-called 'No Mobile Feed' have just that the worst resolution 320x240.

**Comment by marabu88** [comment]
I can add only one. The program for recording with chaturbate uses rtmpdump and I have no problems except the desynchronization of sound on some channels, but this happens on the transmitting side.

I do not know what happened, but records of ts-threads with mfc now occur with a huge number of failures. I do not think it's the fault of my computer or ISP. I tried to use a proxy and got even more errors in the end.

I think that working variant using rtmpdump would solve all the problems at once.

**Comment by horacio9a** [comment]
My English is not the best but we have 'translate.google.ru' which does not translate perfectly but can be corrected a little bit later. It seems that some others Russians know the solution that is bothering you, for example @ruzzy with which I am not in the best relationship. 
Look at his solution at: https://vimeo.com/201450731 and also http://stream-recorder.com/forum/www-myfreecams-com-can-record-free-sex-p89595.html#post89595 where is talking about 'enable a javascript support in your "patched" rtmpdump' ;)

**Comment by marabu88** [comment]
if you wanna know why ts-streams really bad for MFC - just check this video. And this is hapened sometime really long time.
http://www.mediafire.com/file/l2y3r8an1x8npcs/MiaAmelia_2017-08-20_19-57-15.ts

**Comment by horacio9a** [comment]
The difference obviously exists as it can be seen from the attached picture.
Check the ffmpeg.exe version you are using and try to record the MFC with another version of the MFC Recorder until you find the error.

![2383](https://user-images.githubusercontent.com/17076459/29498997-9aa4c8a4-8607-11e7-924e-6de113ec614a.jpg)

**Comment by marabu88** [comment]
horacio9a, i just cut this video from more long. sorry. but this problem have all 3 (!) variant this videos - 2 recordet with ffmpeg and 1 - streamlink. i think this is not my problem.

**Comment by sstativa** [comment]
I've never used `streamlink` therefore cannot so sure, but a quick look gives an idea that it's just another "wrapper" on top of `ffmpeg`. In this case I would recommend you to try different versions of `ffmpeg`.

**Comment by horacio9a** [comment]
Can you test with my last mfc.exe (http://stream-recorder.com/forum/showpost.php?p=93352&postcount=1164)?
Try record in both formats (ts & flv). If, for example, FLV is ok it will not be a problem later converted to another format.

**Comment by marabu88** [comment]
sstativa, if streamlink is a wrapper, then why does not it call ffmpeg? I think this program has its own bootloader. In favor of this is the fact that if ffmpeg creates one file with a lot of gaps, streamlink creates more files, but they do not have errors inside.

**Comment by marabu88** [comment]
And I still hope to get an answer about rtmpdump. I hate to think that you are the only person on the ground who can write streams with this program without using an external adobe player and you will keep this information closed for an unknown reason to me.

**Comment by horacio9a** [comment]
If the wrapper is in question, it might be helpful to add -f (force format) like this:

ffmpeg -i (url) -c copy -vsync 2 -r 60 -b:v 500k -f ts (path + filename)

**Comment by marabu88** [comment]
sstativa, I think I did not read your message about coffee. I understand you now, but you want this amount of money personally from me, since no one else seems to be interested in this matter. Personally I do not use your program to make money, because I would like to receive a working solution solely for personal use and only for the reason that I have problems with ffmpeg. As well as you I am engaged in programming, but at the moment I have not studied issues related to video streams deep enough. And I need your support as a colleague, not as a sales person.

**Comment by marabu88** [comment]
sstativa, you just ignore me..nice....

**Comment by horacio9a** [comment]
Марабу, нет необходимости писать по-русски, потому что я уже говорил вам, что есть translate.google.ru. Мне просто нравится, что вы думаете об этом как о моем хобби, и я никогда не думал о том, чтобы искать деньги для этого, но по этой причине вы не должны обвинять людей, которые не понимают это, как я и вы, например. В отличие от большинства других, он по-прежнему готов поделиться частью своих знаний с другими людьми, в отличие от других, таких как @ruzzy, о которых я уже упоминал в негативном контексте. Я молюсь, чтобы вы не утруждали себя такими моральными дискуссиями. Вы должны понимать, что лучше хранить что-то секретное для большинства, иначе кто-то пытается сделать этот секрет раньше и больше не работать должным образом. Вот почему существуют различные форумы с небольшим количеством людей, которые могут доверять, и которые могут обмениваться этими секретами, не опасаясь, что не смогут этого сделать в ближайшее время. Если вы хотите быть участником одного из этих форумов, не стесняйтесь обращаться ко мне с личным сообщением на форуме SR. Я из славянского происхождения, но я не русский, и я надеюсь, что перевод перевел это на русский, чтобы он не потерял смысла.

**Comment by marabu88** [comment]
horacio9a, thanks fro your comment. I think i can use russian language for answer. I apologize for the emotions also

Не знаю каков Ваш родной язык, но я все понял. К сожалению goole-транслятор переводит с русского языка очень часто некорректно. Мне приходится максимально упрощать фразы и даже строить их так как они будут выглядеть на английском. Боюсь, что часто это приводит к тому, что сказанное мной искажается очень сильно.

К Вам у меня нет никаких претензий, Вы делаете то, что можете и я Вам признателен, но меня угнетает тот факт, что Сергей (разработчик оригинального скрипта) отлична меня понимает, наверняка знает, что происходит в России сейчас и ведет себя так отстранено. Если Сергей волнуется, что его информация попадет в чужие руки, то это совершенно напрасно. В первую очередь я занимаюсь адаптацией его кода под свои нужды и, как я уже сказал, я не зарабатываю не этом!!! Мне казалось, что сообщество программистов всегда поддерживало друг-друга и этим мы выгодно отличаемся от всех этих гребаных торгашей и политиков.

Сейчас я трачу ОЧЕНЬ много времени разгребая видео, скачанное в 4-х (!) экземплярах. И я очень рассчитывал на помощь в решении данной проблемы. Потому, если все же Сергей, Вы или кто-нибудь еще согласитесь помочь мне, пишите на marabu88@hotmail.com (email for contact with me)

Я лишь могу пообещать, что ничего не будет опубликовано без согласия автора. Мне важнее иметь доверительные отношения с людьми, которые занимаются тем же делом что и я, вместо сиюминутной выгоды.

And thanks to everyone who supports this project.

**Comment by sstativa** [comment]
As mentioned above

> Let's do it this way, if one day I rich the goal in 333 coffees, I'll release my private version of the script with rtmpdump support.
