### ISSUE TITLE
Video size

### ISSUE THREAD

**Issue by makoshark2001** [sstativa/mfc-node#46]
Is there anyway to increase the resolution captured? The output seems really small.

**Comment by abcminer** [comment]
From all the feeds I've seen, it depends on how the model is sending her content. I've seen small and large from the same model within the same day. If you try saving at a larger resolution than original stream, well, you know what will happen...I hope.

**Comment by sstativa** [comment]
There is no way to control resolutions. 

In case of `rtmpdump` you record the "native" resolution selected by the model, in case of `ffmpeg`, `ffmpeg` tries to select the highest resolution available in m3u8 file.
