### ISSUE TITLE
Updated Servers

### ISSUE THREAD

**Issue by zlez93** [sstativa/mfc-node#5]
Hello,

First of all thank-you very much for creating this tool. I managed to use it for the past couple days but unluckily it appears that MFCs servers have been updated and I keep receiving a time out error in the console.

Will you be updating this? Or is there anyone out there that can give me some tips so that I can update it myself?

**Comment by renzer0** [comment]
I can confirm this :( I hope it gets updated soon. Thank you for this great tool

**Comment by k3admm** [comment]
[ERROR] TimeoutError: operation timed out.

Thanks for this tool.

**Comment by sstativa** [comment]
It looks like the url to retrieve online models has been changed. Some fields, like city or country are gone... 

I made a temporary fix, I have no time to work it properly, should work for some time.

**Comment by k3admm** [comment]
Thank you very much

**Comment by marabu88** [comment]
don't work again

**Comment by sstativa** [comment]
Please, before make any comments, check the site first. If myfreecams.com is down is obviously not a script problem.
