### ISSUE TITLE
Patched Rtmpdump detected but only HD recording support

### ISSUE THREAD

**Issue by hadex394** [sstativa/mfc-node#54]
I'm trying your last update with your patched rtmpdump and debug is returning "Patched Rtmpdump Detected" and also "Only HD recording support". It's also showing only HD models to record but it's not able to. Regular rtmpdump is working fine showing/recording HD models. 

Maybe you have updated your patched rtmpdump and thats why I'm getting that error but wanted to let you know.

Thank you as always for your work!

**Comment by sstativa** [comment]
Whoops, my bad. I was trying to make a workaround without recompiling `rtmpdump` And it looks like I failed. 

For now I have an updated rtmdump only for linux and macos, it will take me  sometime to build Windows version.

**Comment by Asynchr0nous** [comment]
Any chances you could also attach macOS version of rtmpdump? would greatly appreciate it. Thanks
