### ISSUE TITLE
Request: move filename format to config

### ISSUE THREAD

**Issue by marabu88** [sstativa/mfc-node#7]
Subj :)

**Comment by horacio9a** [comment]
That's is no problem :)

Add line 'dateFormat: DDMMYYYY-HHmmss' in config.yml

Replace line 19 of main.js 'return moment().format('YYYY-MM-DDTHHmmss');'
with 'return moment().format(config.dateFormat);'

**Comment by horacio9a** [comment]
I have finally published my version of @sstativa MFC Recorder at: [https://github.com/horacio9a/mfc-node](https://github.com/horacio9a/mfc-node).
Filename format is in config.yml + 'picture preview' + recording in FLV format and some more improving.
